apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-deployment
  namespace: vaultwarden
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        env:
        - name: SIGNUPS_ALLOWED
          value: "true"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vaultwarden
          mountPath: /data
      volumes:
      - name: vaultwarden
        persistentVolumeClaim:
          claimName: vaultwarden-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-service
  namespace: vaultwarden
spec:
  selector:
    app: vaultwarden
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
    nodePort: 30001
  type: NodePort
