apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-deployment
  namespace: vaultwarden
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        env:
        - name: SIGNUPS_ALLOWED
          value: "true"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vaultwarden
          mountPath: /data
      volumes:
      - name: vaultwarden
        persistentVolumeClaim:
          claimName: vaultwarden-pvc
